import { NextResponse } from 'next/server';
import { db } from '@/lib/firebase';
import { collection, getDocs, addDoc, query, where, orderBy, limit, Timestamp } from 'firebase/firestore';

// Helper function to format Thai month
function formatThaiMonth(date) {
  const months = ['มกราคม', 'กุมภาพันธ์', 'มีนาคม', 'เมษายน', 'พฤษภาคม', 'มิถุนายน',
                  'กรกฎาคม', 'สิงหาคม', 'กันยายน', 'ตุลาคม', 'พฤศจิกายน', 'ธันวาคม'];
  const thaiYear = date.getFullYear() + 543;
  return `${date.getDate()} ${months[date.getMonth()]} ${thaiYear}`;
}

// Helper function to get date range for current month
function getCurrentMonthRange() {
  const now = new Date();
  const startOfMonth = new Date(now.getFullYear(), now.getMonth(), 1);
  const endOfMonth = new Date(now.getFullYear(), now.getMonth() + 1, 0, 23, 59, 59);
  return { startOfMonth, endOfMonth };
}

// Helper function to get date range for last 30 days
function getLast30DaysRange() {
  const now = new Date();
  const thirtyDaysAgo = new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000);
  return { start: thirtyDaysAgo, end: now };
}

// Generate fishing activity news
async function generateFishingNews() {
  try {
    const { startOfMonth, endOfMonth } = getCurrentMonthRange();

    const fishingRecordsRef = collection(db, 'fishingRecords');
    const q = query(
      fishingRecordsRef,
      where('verified', '==', true),
      orderBy('date', 'desc')
    );

    const snapshot = await getDocs(q);
    let totalWeight = 0;
    let totalRecords = 0;
    let uniqueSpecies = new Set();
    let fishPhoto = null;

    snapshot.forEach(doc => {
      const data = doc.data();
      const recordDate = data.date?.toDate ? data.date.toDate() : new Date(data.date);

      if (recordDate >= startOfMonth && recordDate <= endOfMonth) {
        totalRecords++;
        totalWeight += parseFloat(data.totalWeight) || 0;

        // Collect unique species
        if (data.fishList && Array.isArray(data.fishList)) {
          data.fishList.forEach(fish => {
            if (fish.name || fish.species) {
              uniqueSpecies.add(fish.name || fish.species);
              // Get first fish photo
              if (!fishPhoto && fish.photo) {
                fishPhoto = fish.photo;
              }
            }
          });
        }
      }
    });

    if (totalRecords > 0) {
      const now = new Date();
      const monthName = formatThaiMonth(now).split(' ')[1]; // Get month name only

      return {
        title: `กิจกรรมการจับปลาเดือน${monthName} บันทึกได้ ${totalWeight.toFixed(1)} กิโลกรัม`,
        summary: `ในเดือน${monthName}นี้มีการบันทึกการจับปลาจำนวน ${totalRecords} ครั้ง น้ำหนักรวม ${totalWeight.toFixed(1)} กิโลกรัม พบปลา ${uniqueSpecies.size} ชนิด แสดงให้เห็นถึงความหลากหลายทางชีวภาพของแม่น้ำโขงที่ยังคงอุดมสมบูรณ์`,
        category: 'การจับปลา',
        image: fishPhoto || 'https://placehold.co/400x250/1976d2/ffffff?text=Fishing+Activity',
        source: 'fishingRecords',
        date: formatThaiMonth(now),
        autoGenerated: true,
        isPinned: false
      };
    }

    return null;
  } catch (error) {
    console.error('Error generating fishing news:', error);
    return null;
  }
}

// Generate rare fish news
async function generateRareFishNews() {
  try {
    const { start, end } = getLast30DaysRange();

    // Get rare fish species (CR, EN, VU)
    const speciesRef = collection(db, 'fish_species');
    const speciesSnapshot = await getDocs(speciesRef);

    const rareSpeciesMap = new Map();
    speciesSnapshot.forEach(doc => {
      const data = doc.data();
      const status = data.iucn_status || data.conservation_status;
      if (['CR', 'EN', 'VU'].includes(status)) {
        const name = data.thai_name || data.common_name_thai || data.scientific_name;
        if (name) {
          rareSpeciesMap.set(name.toLowerCase(), {
            name: name,
            status: status,
            statusThai: status === 'CR' ? 'ใกล้สูญพันธุ์อย่างยิ่ง' :
                       status === 'EN' ? 'ใกล้สูญพันธุ์' : 'เสี่ยงต่อการสูญพันธุ์'
          });
        }
      }
    });

    // Check fishing records for rare fish
    const fishingRecordsRef = collection(db, 'fishingRecords');
    const q = query(
      fishingRecordsRef,
      where('verified', '==', true),
      orderBy('date', 'desc'),
      limit(100)
    );

    const snapshot = await getDocs(q);
    let rareFishFound = [];

    snapshot.forEach(doc => {
      const data = doc.data();
      const recordDate = data.date?.toDate ? data.date.toDate() : new Date(data.date);

      if (recordDate >= start && recordDate <= end) {
        if (data.fishList && Array.isArray(data.fishList)) {
          data.fishList.forEach(fish => {
            const fishName = (fish.name || fish.species || '').toLowerCase();
            if (rareSpeciesMap.has(fishName)) {
              rareFishFound.push({
                ...rareSpeciesMap.get(fishName),
                count: parseInt(fish.count) || 1,
                weight: parseFloat(fish.weight) || 0,
                photo: fish.photo || null,
                date: recordDate
              });
            }
          });
        }
      }
    });

    if (rareFishFound.length > 0) {
      const mostRecent = rareFishFound[0];
      const totalCount = rareFishFound.reduce((sum, f) => sum + f.count, 0);

      return {
        title: `พบปลา${mostRecent.name} (${mostRecent.statusThai}) จำนวน ${totalCount} ตัว ใน 30 วันที่ผ่านมา`,
        summary: `มีการบันทึกการพบปลา${mostRecent.name} ซึ่งอยู่ในสถานะ ${mostRecent.statusThai} ตามบัญชี IUCN จำนวนทั้งสิ้น ${totalCount} ตัว แสดงให้เห็นว่าพื้นที่แม่น้ำโขงยังคงเป็นแหล่งที่อยู่อาศัยสำคัญของปลาหายาก จำเป็นต้องมีการอนุรักษ์อย่างเข้มงวด`,
        category: 'ปลาหายาก',
        image: mostRecent.photo || 'https://placehold.co/400x250/d32f2f/ffffff?text=Rare+Fish',
        source: 'fishingRecords+fish_species',
        date: formatThaiMonth(new Date()),
        autoGenerated: true,
        isPinned: true
      };
    }

    return null;
  } catch (error) {
    console.error('Error generating rare fish news:', error);
    return null;
  }
}

// Generate water quality news
async function generateWaterLevelNews() {
  try {
    const waterLevelsRef = collection(db, 'waterLevels');
    const q = query(waterLevelsRef, orderBy('date', 'desc'), limit(30));

    const snapshot = await getDocs(q);

    if (snapshot.empty) {
      return null;
    }

    const levels = [];
    snapshot.forEach(doc => {
      const data = doc.data();
      levels.push({
        date: data.date,
        level: parseFloat(data.currentLevel) || 0
      });
    });

    if (levels.length < 2) {
      return null;
    }

    const latestLevel = levels[0].level;
    const avgLevel = levels.reduce((sum, l) => sum + l.level, 0) / levels.length;
    const difference = latestLevel - avgLevel;
    const percentChange = ((difference / avgLevel) * 100).toFixed(1);

    let trend, trendThai, impact, category;
    if (difference > 0.5) {
      trend = 'เพิ่มขึ้น';
      trendThai = 'สูงขึ้น';
      impact = 'ส่งผลดีต่อการวางไข่และขยายพันธุ์ของปลาหลายชนิด';
      category = 'สิ่งแวดล้อม';
    } else if (difference < -0.5) {
      trend = 'ลดลง';
      trendThai = 'ต่ำลง';
      impact = 'อาจส่งผลกระทบต่อระบบนิเวศและการดำรงชีวิตของปลาบางชนิด';
      category = 'สิ่งแวดล้อม';
    } else {
      trend = 'คงที่';
      trendThai = 'อยู่ในระดับปกติ';
      impact = 'เหมาะสมต่อการดำรงชีวิตของสัตว์น้ำและระบบนิเวศ';
      category = 'สิ่งแวดล้อม';
    }

    return {
      title: `ระดับน้ำแม่น้ำโขง${trend} ${Math.abs(difference).toFixed(2)} เมตร`,
      summary: `ข้อมูล 30 วันที่ผ่านมาแสดงให้เห็นว่าระดับน้ำแม่น้ำโขง${trendThai}จากค่าเฉลี่ย ${Math.abs(percentChange)}% ปัจจุบันอยู่ที่ ${latestLevel.toFixed(2)} เมตร ${impact}`,
      category: category,
      image: 'https://placehold.co/400x250/00acc1/ffffff?text=Water+Level',
      source: 'waterLevels',
      date: formatThaiMonth(new Date()),
      autoGenerated: true,
      isPinned: false
    };

  } catch (error) {
    console.error('Error generating water level news:', error);
    return null;
  }
}

// Generate community news
async function generateCommunityNews() {
  try {
    const { start, end } = getLast30DaysRange();

    const usersRef = collection(db, 'users');
    const snapshot = await getDocs(usersRef);

    let newUsers = 0;
    let totalUsers = snapshot.size;

    snapshot.forEach(doc => {
      const data = doc.data();
      const createdAt = data.createdAt?.toDate ? data.createdAt.toDate() : new Date(data.createdAt);

      if (createdAt >= start && createdAt <= end) {
        newUsers++;
      }
    });

    if (newUsers > 0) {
      return {
        title: `ชาวประมงเข้าร่วมโครงการ ${newUsers} คนในเดือนนี้`,
        summary: `ในช่วง 30 วันที่ผ่านมามีชาวประมงและผู้ที่เกี่ยวข้องเข้าร่วมโครงการฐานข้อมูลปลาแม่น้ำโขงเพิ่มขึ้น ${newUsers} คน ยอดสะสมทั้งหมด ${totalUsers} คน แสดงให้เห็นถึงการมีส่วนร่วมของชุมชนในการอนุรักษ์ทรัพยากรธรรมชาติ`,
        category: 'ชุมชน',
        image: 'https://placehold.co/400x250/388e3c/ffffff?text=Community',
        source: 'users',
        date: formatThaiMonth(new Date()),
        autoGenerated: true,
        isPinned: false
      };
    }

    return null;
  } catch (error) {
    console.error('Error generating community news:', error);
    return null;
  }
}

// Main POST handler
export async function POST(request) {
  try {
    // Generate all types of news
    const newsPromises = [
      generateFishingNews(),
      generateRareFishNews(),
      generateWaterLevelNews(),
      generateCommunityNews()
    ];

    const newsResults = await Promise.all(newsPromises);
    const validNews = newsResults.filter(news => news !== null);

    if (validNews.length === 0) {
      return NextResponse.json({
        success: false,
        message: 'ไม่มีข้อมูลเพียงพอในการสร้างข่าว',
        generated: 0
      });
    }

    // Save to newsArticles collection
    const newsArticlesRef = collection(db, 'newsArticles');
    const savePromises = validNews.map(news =>
      addDoc(newsArticlesRef, {
        ...news,
        createdAt: Timestamp.now(),
        publishedAt: Timestamp.now()
      })
    );

    await Promise.all(savePromises);

    return NextResponse.json({
      success: true,
      message: `สร้างข่าวสำเร็จ ${validNews.length} ข่าว`,
      generated: validNews.length,
      news: validNews
    });

  } catch (error) {
    console.error('Error in news generation:', error);
    return NextResponse.json({
      success: false,
      message: 'เกิดข้อผิดพลาดในการสร้างข่าว',
      error: error.message
    }, { status: 500 });
  }
}

// GET handler to preview news without saving
export async function GET(request) {
  try {
    const newsPromises = [
      generateFishingNews(),
      generateRareFishNews(),
      generateWaterLevelNews(),
      generateCommunityNews()
    ];

    const newsResults = await Promise.all(newsPromises);
    const validNews = newsResults.filter(news => news !== null);

    return NextResponse.json({
      success: true,
      preview: true,
      count: validNews.length,
      news: validNews
    });

  } catch (error) {
    console.error('Error in news preview:', error);
    return NextResponse.json({
      success: false,
      message: 'เกิดข้อผิดพลาดในการดูตัวอย่างข่าว',
      error: error.message
    }, { status: 500 });
  }
}
