'use client';

import { useState, useEffect } from 'react';
import DashboardLayout from '@/components/Layout/DashboardLayout';
import {
  Box,
  Typography,
  Button,
  TextField,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  Paper,
  IconButton,
  Chip,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  FormControl,
  InputLabel,
  Select,
  MenuItem,
  CircularProgress,
  Alert,
  Snackbar,
  Checkbox,
  FormControlLabel
} from '@mui/material';
import {
  Add,
  Edit,
  Delete,
  Visibility,
  Search,
  Cloud,
  PushPin,
  PushPinOutlined
} from '@mui/icons-material';
import { collection, getDocs, addDoc, updateDoc, deleteDoc, doc, query, orderBy, Timestamp } from 'firebase/firestore';
import { ref, uploadBytes, getDownloadURL } from 'firebase/storage';
import { db, storage } from '@/lib/firebase';
import { useAuth } from '@/contexts/AuthContext';

const NewsManagementPage = () => {
  const { userProfile } = useAuth();
  const [news, setNews] = useState([]);
  const [loading, setLoading] = useState(true);
  const [searchTerm, setSearchTerm] = useState('');
  const [categoryFilter, setCategoryFilter] = useState('all');

  // Modal states
  const [addModalOpen, setAddModalOpen] = useState(false);
  const [editModalOpen, setEditModalOpen] = useState(false);
  const [deleteModalOpen, setDeleteModalOpen] = useState(false);
  const [viewModalOpen, setViewModalOpen] = useState(false);
  const [selectedNews, setSelectedNews] = useState(null);

  // Form states
  const [formData, setFormData] = useState({
    title: '',
    summary: '',
    category: '',
    content: '',
    image: '',
    videoUrl: '',
    isPinned: false
  });
  const [imageFile, setImageFile] = useState(null);
  const [imagePreview, setImagePreview] = useState('');
  const [uploadingImage, setUploadingImage] = useState(false);

  // Snackbar
  const [snackbar, setSnackbar] = useState({ open: false, message: '', severity: 'success' });

  const categories = [
    'การจับปลา',
    'ปลาหายาก',
    'สิ่งแวดล้อม',
    'ชุมชน',
    'การอนุรักษ์',
    'การวิจัย',
    'อื่นๆ'
  ];

  // Fetch news from Firestore
  useEffect(() => {
    fetchNews();
  }, []);

  const fetchNews = async () => {
    try {
      setLoading(true);
      const newsRef = collection(db, 'newsArticles');
      const q = query(newsRef, orderBy('publishedAt', 'desc'));
      const snapshot = await getDocs(q);

      const newsData = [];
      snapshot.forEach(doc => {
        newsData.push({
          id: doc.id,
          ...doc.data()
        });
      });

      setNews(newsData);
      setLoading(false);
    } catch (error) {
      console.error('Error fetching news:', error?.message || error);
      setSnackbar({ open: true, message: `เกิดข้อผิดพลาดในการโหลดข่าว: ${error?.message || error}`, severity: 'error' });
      setLoading(false);
    }
  };

  // Generate auto news
  const handleGenerateNews = async () => {
    try {
      setLoading(true);
      const response = await fetch('/api/news/generate', {
        method: 'POST'
      });

      const result = await response.json();

      if (result.success) {
        setSnackbar({
          open: true,
          message: `สร้างข่าวสำเร็จ ${result.generated} ข่าว`,
          severity: 'success'
        });
        fetchNews(); // Refresh list
      } else {
        setSnackbar({
          open: true,
          message: result.message || 'ไม่สามารถสร้างข่าวได้',
          severity: 'error'
        });
      }

      setLoading(false);
    } catch (error) {
      console.error('Error generating news:', error);
      setSnackbar({ open: true, message: 'เกิดข้อผิดพลาดในการสร้างข่าว', severity: 'error' });
      setLoading(false);
    }
  };

  // Add news
  const handleAddNews = async () => {
    try {
      if (!formData.title || !formData.summary || !formData.category) {
        setSnackbar({ open: true, message: 'กรุณากรอกข้อมูลที่จำเป็น', severity: 'warning' });
        return;
      }

      setUploadingImage(true);
      // Create doc first to get ID for storage path
      const newsRef = collection(db, 'newsArticles');
      const docRef = await addDoc(newsRef, {
        ...formData,
        image: '',
        autoGenerated: false,
        author: userProfile?.displayName || userProfile?.email || 'Admin',
        authorId: userProfile?.uid || '',
        date: new Date().toLocaleDateString('th-TH', { day: 'numeric', month: 'long', year: 'numeric' }),
        publishedAt: Timestamp.now(),
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now()
      });

      // Upload image if selected
      if (imageFile) {
        const imageUrl = await uploadImageFile(docRef.id);
        if (imageUrl) {
          await updateDoc(doc(db, 'newsArticles', docRef.id), { image: imageUrl });
        }
      }

      setUploadingImage(false);
      setSnackbar({ open: true, message: 'เพิ่มข่าวสำเร็จ', severity: 'success' });
      setAddModalOpen(false);
      resetForm();
      fetchNews();
    } catch (error) {
      console.error('Error adding news:', error);
      setUploadingImage(false);
      setSnackbar({ open: true, message: 'เกิดข้อผิดพลาดในการเพิ่มข่าว', severity: 'error' });
    }
  };

  // Edit news
  const handleEditNews = async () => {
    try {
      if (!formData.title || !formData.summary || !formData.category) {
        setSnackbar({ open: true, message: 'กรุณากรอกข้อมูลที่จำเป็น', severity: 'warning' });
        return;
      }

      setUploadingImage(true);
      let imageUrl = formData.image;
      if (imageFile) {
        imageUrl = await uploadImageFile(selectedNews.id);
      }

      const newsDoc = doc(db, 'newsArticles', selectedNews.id);
      await updateDoc(newsDoc, {
        title: formData.title,
        summary: formData.summary,
        category: formData.category,
        content: formData.content,
        image: imageUrl || '',
        videoUrl: formData.videoUrl || '',
        isPinned: formData.isPinned,
        updatedAt: Timestamp.now()
      });

      setUploadingImage(false);
      setSnackbar({ open: true, message: 'แก้ไขข่าวสำเร็จ', severity: 'success' });
      setEditModalOpen(false);
      resetForm();
      fetchNews();
    } catch (error) {
      console.error('Error editing news:', error);
      setUploadingImage(false);
      setSnackbar({ open: true, message: 'เกิดข้อผิดพลาดในการแก้ไขข่าว', severity: 'error' });
    }
  };

  // Delete news
  const handleDeleteNews = async () => {
    try {
      const newsDoc = doc(db, 'newsArticles', selectedNews.id);
      await deleteDoc(newsDoc);

      setSnackbar({ open: true, message: 'ลบข่าวสำเร็จ', severity: 'success' });
      setDeleteModalOpen(false);
      setSelectedNews(null);
      fetchNews();
    } catch (error) {
      console.error('Error deleting news:', error);
      setSnackbar({ open: true, message: 'เกิดข้อผิดพลาดในการลบข่าว', severity: 'error' });
    }
  };

  // Toggle pin
  const handleTogglePin = async (newsItem) => {
    try {
      const newsDoc = doc(db, 'newsArticles', newsItem.id);
      await updateDoc(newsDoc, {
        isPinned: !newsItem.isPinned,
        updatedAt: Timestamp.now()
      });

      setSnackbar({
        open: true,
        message: newsItem.isPinned ? 'ยกเลิกปักหมุดแล้ว' : 'ปักหมุดข่าวแล้ว',
        severity: 'success'
      });
      fetchNews();
    } catch (error) {
      console.error('Error toggling pin:', error);
      setSnackbar({ open: true, message: 'เกิดข้อผิดพลาด', severity: 'error' });
    }
  };

  // Open modals
  const openAddModal = () => {
    resetForm();
    setAddModalOpen(true);
  };

  const openEditModal = (newsItem) => {
    setSelectedNews(newsItem);
    setFormData({
      title: newsItem.title || '',
      summary: newsItem.summary || '',
      category: newsItem.category || '',
      content: newsItem.content || '',
      image: newsItem.image || '',
      videoUrl: newsItem.videoUrl || '',
      isPinned: newsItem.isPinned || false
    });
    setImageFile(null);
    setImagePreview(newsItem.image || '');
    setEditModalOpen(true);
  };

  const openDeleteModal = (newsItem) => {
    setSelectedNews(newsItem);
    setDeleteModalOpen(true);
  };

  const openViewModal = (newsItem) => {
    setSelectedNews(newsItem);
    setViewModalOpen(true);
  };

  const resetForm = () => {
    setFormData({
      title: '',
      summary: '',
      category: '',
      content: '',
      image: '',
      videoUrl: '',
      isPinned: false
    });
    setImageFile(null);
    setImagePreview('');
    setSelectedNews(null);
  };

  const handleImageFileChange = (e) => {
    const file = e.target.files?.[0];
    if (!file) return;
    setImageFile(file);
    setImagePreview(URL.createObjectURL(file));
  };

  const uploadImageFile = async (newsId) => {
    if (!imageFile) return null;
    const timestamp = Date.now();
    const storageRef = ref(storage, `news/${newsId}/${timestamp}.jpg`);
    await uploadBytes(storageRef, imageFile);
    return await getDownloadURL(storageRef);
  };

  const getYouTubeEmbedUrl = (url) => {
    if (!url) return null;
    const match = url.match(/(?:youtube\.com\/watch\?v=|youtu\.be\/|youtube\.com\/embed\/|youtube\.com\/shorts\/)([^&?/]+)/);
    if (match) return `https://www.youtube.com/embed/${match[1]}`;
    return null;
  };

  // Filter news
  const filteredNews = news.filter(item => {
    const matchesSearch = item.title?.toLowerCase().includes(searchTerm.toLowerCase()) ||
                          item.summary?.toLowerCase().includes(searchTerm.toLowerCase());
    const matchesCategory = categoryFilter === 'all' || item.category === categoryFilter;
    return matchesSearch && matchesCategory;
  });

  return (
    <DashboardLayout>
      <Box sx={{ p: 3 }}>
        <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 3 }}>
          <Typography variant="h4" fontWeight="bold">
            จัดการข่าว
          </Typography>
          <Box sx={{ display: 'flex', gap: 2 }}>
            <Button
              variant="outlined"
              color="primary"
              startIcon={<Cloud />}
              onClick={handleGenerateNews}
              disabled={loading}
            >
              สร้างข่าวอัตโนมัติ
            </Button>
            <Button
              variant="contained"
              color="primary"
              startIcon={<Add />}
              onClick={openAddModal}
            >
              เขียนข่าวเอง
            </Button>
          </Box>
        </Box>

        {/* Search and Filter */}
        <Paper sx={{ p: 2, mb: 3 }}>
          <Box sx={{ display: 'flex', gap: 2 }}>
            <TextField
              placeholder="ค้นหาข่าว..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              InputProps={{
                startAdornment: <Search sx={{ mr: 1, color: 'text.secondary' }} />
              }}
              sx={{ flex: 1 }}
            />
            <FormControl sx={{ minWidth: 200 }}>
              <InputLabel>หมวดหมู่</InputLabel>
              <Select
                value={categoryFilter}
                onChange={(e) => setCategoryFilter(e.target.value)}
                label="หมวดหมู่"
              >
                <MenuItem value="all">ทั้งหมด</MenuItem>
                {categories.map(cat => (
                  <MenuItem key={cat} value={cat}>{cat}</MenuItem>
                ))}
              </Select>
            </FormControl>
          </Box>
        </Paper>

        {/* News Table */}
        <TableContainer component={Paper}>
          <Table>
            <TableHead>
              <TableRow>
                <TableCell><strong>หัวข้อ</strong></TableCell>
                <TableCell><strong>หมวดหมู่</strong></TableCell>
                <TableCell><strong>ผู้สร้าง</strong></TableCell>
                <TableCell><strong>วันที่</strong></TableCell>
                <TableCell><strong>สถานะ</strong></TableCell>
                <TableCell align="center"><strong>การจัดการ</strong></TableCell>
              </TableRow>
            </TableHead>
            <TableBody>
              {loading ? (
                <TableRow>
                  <TableCell colSpan={6} align="center" sx={{ py: 4 }}>
                    <CircularProgress />
                  </TableCell>
                </TableRow>
              ) : filteredNews.length === 0 ? (
                <TableRow>
                  <TableCell colSpan={6} align="center" sx={{ py: 4 }}>
                    <Typography color="text.secondary">ไม่พบข่าว</Typography>
                  </TableCell>
                </TableRow>
              ) : (
                filteredNews.map((item) => (
                  <TableRow key={item.id} hover>
                    <TableCell>
                      <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                        {item.isPinned && <PushPin fontSize="small" color="primary" />}
                        <Typography>{item.title}</Typography>
                      </Box>
                    </TableCell>
                    <TableCell>
                      <Chip label={item.category} size="small" color="primary" variant="outlined" />
                    </TableCell>
                    <TableCell>
                      {item.autoGenerated ? (
                        <Chip label="อัตโนมัติ" size="small" color="info" icon={<Cloud />} />
                      ) : (
                        item.author || 'Admin'
                      )}
                    </TableCell>
                    <TableCell>{item.date}</TableCell>
                    <TableCell>
                      {item.isPinned && (
                        <Chip label="ปักหมุด" size="small" color="secondary" />
                      )}
                    </TableCell>
                    <TableCell align="center">
                      <IconButton size="small" onClick={() => openViewModal(item)} title="ดูข่าว">
                        <Visibility fontSize="small" />
                      </IconButton>
                      <IconButton size="small" onClick={() => openEditModal(item)} title="แก้ไข">
                        <Edit fontSize="small" />
                      </IconButton>
                      <IconButton size="small" onClick={() => handleTogglePin(item)} title={item.isPinned ? "ยกเลิกปักหมุด" : "ปักหมุด"}>
                        {item.isPinned ? <PushPin fontSize="small" /> : <PushPinOutlined fontSize="small" />}
                      </IconButton>
                      <IconButton
                        size="small"
                        onClick={() => openDeleteModal(item)}
                        color="error"
                        title="ลบ"
                      >
                        <Delete fontSize="small" />
                      </IconButton>
                    </TableCell>
                  </TableRow>
                ))
              )}
            </TableBody>
          </Table>
        </TableContainer>

        {/* Add News Modal */}
        <Dialog open={addModalOpen} onClose={() => setAddModalOpen(false)} maxWidth="md" fullWidth>
          <DialogTitle>เขียนข่าวเอง</DialogTitle>
          <DialogContent>
            <Box sx={{ display: 'flex', flexDirection: 'column', gap: 2, mt: 2 }}>
              <TextField
                label="หัวข้อข่าว"
                required
                fullWidth
                value={formData.title}
                onChange={(e) => setFormData({ ...formData, title: e.target.value })}
              />
              <FormControl fullWidth required>
                <InputLabel>หมวดหมู่</InputLabel>
                <Select
                  value={formData.category}
                  onChange={(e) => setFormData({ ...formData, category: e.target.value })}
                  label="หมวดหมู่"
                >
                  {categories.map(cat => (
                    <MenuItem key={cat} value={cat}>{cat}</MenuItem>
                  ))}
                </Select>
              </FormControl>
              <TextField
                label="สรุปข่าว"
                required
                fullWidth
                multiline
                rows={3}
                value={formData.summary}
                onChange={(e) => setFormData({ ...formData, summary: e.target.value })}
              />
              <TextField
                label="เนื้อหาข่าวฉบับเต็ม"
                fullWidth
                multiline
                rows={8}
                value={formData.content}
                onChange={(e) => setFormData({ ...formData, content: e.target.value })}
              />
              {/* Image upload */}
              <Box>
                <Typography variant="body2" color="text.secondary" sx={{ mb: 1 }}>รูปภาพปก</Typography>
                <Button variant="outlined" component="label" size="small">
                  เลือกรูปภาพ
                  <input type="file" accept="image/*" hidden onChange={handleImageFileChange} />
                </Button>
                {imagePreview && (
                  <Box component="img" src={imagePreview} alt="preview"
                    sx={{ display: 'block', mt: 1, maxHeight: 180, maxWidth: '100%', objectFit: 'cover', borderRadius: 1 }}
                  />
                )}
              </Box>
              <TextField
                label="URL วีดีโอ YouTube"
                fullWidth
                value={formData.videoUrl}
                onChange={(e) => setFormData({ ...formData, videoUrl: e.target.value })}
                placeholder="https://www.youtube.com/watch?v=..."
              />
              <FormControlLabel
                control={
                  <Checkbox
                    checked={formData.isPinned}
                    onChange={(e) => setFormData({ ...formData, isPinned: e.target.checked })}
                  />
                }
                label="ปักหมุดข่าวนี้"
              />
            </Box>
          </DialogContent>
          <DialogActions>
            <Button onClick={() => setAddModalOpen(false)}>ยกเลิก</Button>
            <Button onClick={handleAddNews} variant="contained" disabled={uploadingImage}>
              {uploadingImage ? 'กำลังอัปโหลด...' : 'เพิ่มข่าว'}
            </Button>
          </DialogActions>
        </Dialog>

        {/* Edit News Modal */}
        <Dialog open={editModalOpen} onClose={() => setEditModalOpen(false)} maxWidth="md" fullWidth>
          <DialogTitle>แก้ไขข่าว</DialogTitle>
          <DialogContent>
            <Box sx={{ display: 'flex', flexDirection: 'column', gap: 2, mt: 2 }}>
              <TextField
                label="หัวข้อข่าว"
                required
                fullWidth
                value={formData.title}
                onChange={(e) => setFormData({ ...formData, title: e.target.value })}
              />
              <FormControl fullWidth required>
                <InputLabel>หมวดหมู่</InputLabel>
                <Select
                  value={formData.category}
                  onChange={(e) => setFormData({ ...formData, category: e.target.value })}
                  label="หมวดหมู่"
                >
                  {categories.map(cat => (
                    <MenuItem key={cat} value={cat}>{cat}</MenuItem>
                  ))}
                </Select>
              </FormControl>
              <TextField
                label="สรุปข่าว"
                required
                fullWidth
                multiline
                rows={3}
                value={formData.summary}
                onChange={(e) => setFormData({ ...formData, summary: e.target.value })}
              />
              <TextField
                label="เนื้อหาข่าวฉบับเต็ม"
                fullWidth
                multiline
                rows={8}
                value={formData.content}
                onChange={(e) => setFormData({ ...formData, content: e.target.value })}
              />
              {/* Image upload */}
              <Box>
                <Typography variant="body2" color="text.secondary" sx={{ mb: 1 }}>รูปภาพปก</Typography>
                <Button variant="outlined" component="label" size="small">
                  เลือกรูปภาพ
                  <input type="file" accept="image/*" hidden onChange={handleImageFileChange} />
                </Button>
                {imagePreview && (
                  <Box component="img" src={imagePreview} alt="preview"
                    sx={{ display: 'block', mt: 1, maxHeight: 180, maxWidth: '100%', objectFit: 'cover', borderRadius: 1 }}
                  />
                )}
              </Box>
              <TextField
                label="URL วีดีโอ YouTube"
                fullWidth
                value={formData.videoUrl}
                onChange={(e) => setFormData({ ...formData, videoUrl: e.target.value })}
                placeholder="https://www.youtube.com/watch?v=..."
              />
              <FormControlLabel
                control={
                  <Checkbox
                    checked={formData.isPinned}
                    onChange={(e) => setFormData({ ...formData, isPinned: e.target.checked })}
                  />
                }
                label="ปักหมุดข่าวนี้"
              />
            </Box>
          </DialogContent>
          <DialogActions>
            <Button onClick={() => setEditModalOpen(false)}>ยกเลิก</Button>
            <Button onClick={handleEditNews} variant="contained" disabled={uploadingImage}>
              {uploadingImage ? 'กำลังอัปโหลด...' : 'บันทึก'}
            </Button>
          </DialogActions>
        </Dialog>

        {/* View News Modal */}
        <Dialog open={viewModalOpen} onClose={() => setViewModalOpen(false)} maxWidth="md" fullWidth scroll="paper">
          <DialogTitle>{selectedNews?.title}</DialogTitle>
          <DialogContent dividers>
            {selectedNews && (
              <Box sx={{ display: 'flex', flexDirection: 'column', gap: 2, mt: 1 }}>
                <Box sx={{ display: 'flex', gap: 1, flexWrap: 'wrap', alignItems: 'center' }}>
                  <Chip label={selectedNews.category} color="primary" size="small" />
                  {selectedNews.autoGenerated && (
                    <Chip label="สร้างอัตโนมัติ" color="info" size="small" icon={<Cloud />} />
                  )}
                  {selectedNews.isPinned && (
                    <Chip label="ปักหมุด" color="secondary" size="small" />
                  )}
                  <Typography variant="caption" color="text.secondary" sx={{ ml: 'auto' }}>
                    {selectedNews.date} • {selectedNews.author || 'ระบบอัตโนมัติ'}
                  </Typography>
                </Box>

                {/* รูปภาพ */}
                {selectedNews.image && (
                  <Box
                    component="img"
                    src={selectedNews.image}
                    alt={selectedNews.title}
                    sx={{ width: '100%', maxHeight: 320, objectFit: 'cover', borderRadius: 2 }}
                  />
                )}

                {/* สรุปข่าว */}
                <Box sx={{ bgcolor: '#e3f2fd', borderLeft: '4px solid #1976d2', p: 2, borderRadius: '0 8px 8px 0' }}>
                  <Typography variant="subtitle2" color="text.secondary" sx={{ mb: 0.5 }}>สรุปข่าว</Typography>
                  <Typography variant="body2">{selectedNews.summary}</Typography>
                </Box>

                {/* เนื้อหาฉบับเต็ม */}
                {selectedNews.content && (
                  <>
                    <Typography variant="h6" fontWeight="bold">เนื้อหาฉบับเต็ม</Typography>
                    <Typography sx={{ whiteSpace: 'pre-wrap', lineHeight: 1.9 }}>{selectedNews.content}</Typography>
                  </>
                )}

                {/* วีดีโอ YouTube */}
                {selectedNews.videoUrl && getYouTubeEmbedUrl(selectedNews.videoUrl) && (
                  <>
                    <Typography variant="h6" fontWeight="bold">วีดีโอ</Typography>
                    <Box sx={{ position: 'relative', paddingTop: '56.25%', borderRadius: 2, overflow: 'hidden' }}>
                      <Box
                        component="iframe"
                        src={getYouTubeEmbedUrl(selectedNews.videoUrl)}
                        title="video"
                        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                        allowFullScreen
                        sx={{ position: 'absolute', top: 0, left: 0, width: '100%', height: '100%', border: 0 }}
                      />
                    </Box>
                  </>
                )}
              </Box>
            )}
          </DialogContent>
          <DialogActions>
            <Button onClick={() => setViewModalOpen(false)}>ปิด</Button>
          </DialogActions>
        </Dialog>

        {/* Delete Confirmation Dialog */}
        <Dialog open={deleteModalOpen} onClose={() => setDeleteModalOpen(false)}>
          <DialogTitle>ยืนยันการลบข่าว</DialogTitle>
          <DialogContent>
            <Typography>คุณต้องการลบข่าว &quot;{selectedNews?.title}&quot; หรือไม่?</Typography>
            <Typography color="error" variant="body2" sx={{ mt: 1 }}>
              การลบข่าวนี้ไม่สามารถย้อนกลับได้
            </Typography>
          </DialogContent>
          <DialogActions>
            <Button onClick={() => setDeleteModalOpen(false)}>ยกเลิก</Button>
            <Button onClick={handleDeleteNews} color="error" variant="contained">ลบข่าว</Button>
          </DialogActions>
        </Dialog>

        {/* Snackbar */}
        <Snackbar
          open={snackbar.open}
          autoHideDuration={6000}
          onClose={() => setSnackbar({ ...snackbar, open: false })}
          anchorOrigin={{ vertical: 'bottom', horizontal: 'center' }}
        >
          <Alert onClose={() => setSnackbar({ ...snackbar, open: false })} severity={snackbar.severity}>
            {snackbar.message}
          </Alert>
        </Snackbar>
      </Box>
    </DashboardLayout>
  );
};

export default NewsManagementPage;
